### ISSUE TITLE
建议贴：无法锁定安装器，解决办法

### ISSUE THREAD

**Issue by YamazakuraH** [iamr0s/InstallerX#1]
设备：一加8Pro
系统：ColorOS 13
授权方式：sui
现象：点击“锁定为默认安装器”以及“清除默认安装器”没有任何反应

**Comment by iamr0s** [comment]
ColorOS魔改了锁定，不允许锁定

**Comment by iamr0s** [comment]
如果已经ROOT了，可以用XP模块解决

**Comment by iamr0s** [comment]
[lock installer.zip](https://github.com/iamr0s/InstallerX/files/11285551/lock.installer.zip)
试试这个XP模块

**Comment by iamr0s** [comment]
如果成功了，请及时反馈

**Comment by YamazakuraH** [comment]
可以了

**Comment by YamazakuraH** [comment]
> 如果成功了，请及时反馈

可以了
