### ISSUE TITLE
miui14.0.2shizuku已授权无法替换,请问有什么方法吗?

### ISSUE THREAD

**Issue by yjp183** [iamr0s/InstallerX#2]
Rt

**Comment by iamr0s** [comment]
1. 卸载更新系统安装器，再用Shizuku模式授权锁定。
2. 使用root锁定，做了特别优化
3. 使用我提供的Xposed 模块进行锁定
以上方式选一种

**Comment by yjp183** [comment]
好的,我先试试第一条,感谢回复.
