### ISSUE TITLE
请问如何自定义授权器

### ISSUE THREAD

**Issue by gaozhilai** [iamr0s/InstallerX#3]
请问如何自定义授权其，比如把icebox设置为授权器，好像没看到相关讨论或者文档

**Comment by iamr0s** [comment]
请考虑 [Dhizuku](https://github.com/iamr0s/Dhizuku)

介绍与使用方法：
[金山文档](https://www.kdocs.cn/l/cac6zwMXMPyR)
[酷安](https://www.coolapk.com/feed/45819359?shareKey=ZjI4MDNkMjAwZTI2NjQ2YWVkZGM~&shareUid=1581760&shareFrom=com.coolapk.market_13.1.1)

**Comment by gaozhilai** [comment]
收到, 请问文档里提到的"Lspatch打包的支持Dhizuku接口的应用"在哪里下载呢, 文档里貌似只有Dhizuku本身的下载

**Comment by iamr0s** [comment]
金山文档底部 蓝奏云

**Comment by gaozhilai** [comment]
没有解冻的软件创建了没有名字的用户, 但是冻结软件已经解除了管理员权限, 这时有什么删除隐藏账户的办法吗

**Comment by iamr0s** [comment]
文章内有说明，雹 [酷安](https://www.coolapk.com/apk/com.aistra.hail) [Github](https://github.com/aistra0528/Hail)，它支持调用Shizuku的冻结

**Comment by gaozhilai** [comment]
看到了, 成功设置权限了, 已经冻结的app, 账户不影响设置管理员
