### ISSUE TITLE
已允许测试包，仍无法安装测试包

### ISSUE THREAD

**Issue by Aurora-Simba** [iamr0s/InstallerX#4]
![Screenshot_2023-05-26-15-45-37-61_c33eb1d7cfba59687cd41cc69bb60acd](https://github.com/iamr0s/InstallerX/assets/106955617/417abe01-33dd-41fb-9aa5-6dd3fdce5924)
![Screenshot_2023-05-26-15-45-51-03_c33eb1d7cfba59687cd41cc69bb60acd](https://github.com/iamr0s/InstallerX/assets/106955617/ab2a729f-9089-409d-b706-6258e785a6d1)
已允许测试包，仍无法安装测试包

**Comment by iamr0s** [comment]
换成Shizuku试试

**Comment by iamr0s** [comment]
Dhizuku不被允许安装降级，也许也不被安装测试包
